# Generated by Django 5.2.8 on 2025-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
