# Generated by Django 5.2.8 on 2025-12-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_receipt_generated_order_receipt_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order ( List of all orders )', 'verbose_name_plural': 'Orders ( List of all orders )'},
        ),
    ]
