# Generated by Django 5.2.8 on 2025-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_specifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
