# Generated by Django 5.2.8 on 2025-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_room_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
