# Generated by Django 5.2.8 on 2025-12-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property (Built Homes / House Plans Page)', 'verbose_name_plural': 'Properties (Built Homes / House Plans Page)'},
        ),
    ]
