# Generated by Django 5.2.8 on 2025-12-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
