# Generated by Django 5.2.8 on 2025-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+27 (0) 72 665 9790', max_length=50)),
                ('email', models.EmailField(default='info@cedrichouseplans.co.za', max_length=254)),
                ('support_email', models.EmailField(default='support@cedrichouseplans.co.za', max_length=254)),
                ('address', models.TextField(default='South Africa')),
                ('monday_friday', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('saturday', models.CharField(default='10:00 AM - 4:00 PM', max_length=100)),
                ('sunday', models.CharField(default='Closed', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Cedric House Designs', max_length=100)),
                ('tagline', models.CharField(default='Crafting exceptional homes and dreams', max_length=255)),
                ('hero_title', models.CharField(default='Find Your Perfect House Plan', max_length=255)),
                ('hero_description', models.TextField(default='Discover thousands of professionally designed house plans. From modern minimalist to classic traditional styles.')),
                ('about_title', models.CharField(default='About Cedric House Designs', max_length=255)),
                ('about_description', models.TextField(default='Crafting exceptional homes and dreams for over two decades.')),
                ('who_we_are_content', models.TextField(default='Cedric House Designs is a leading architectural firm...')),
                ('mission_statement', models.TextField(default='To design and deliver exceptional residential homes...')),
                ('years_experience', models.CharField(default='25+', max_length=50)),
                ('projects_completed', models.CharField(default='500+', max_length=50)),
                ('client_satisfaction', models.CharField(default='98%', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Verified Customer', max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('initials', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
