# Generated by Django 5.2.8 on 2025-12-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_certification_planmodification_service_whytrustus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Certification (About Page)', 'verbose_name_plural': 'Certifications (About Page)'},
        ),
        migrations.AlterModelOptions(
            name='planmodification',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Plan Modification (Services Page)', 'verbose_name_plural': 'Plan Modifications (Services Page)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Service (Services Page)', 'verbose_name_plural': 'Services (Services Page)'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Team Member (About Page)', 'verbose_name_plural': 'Team Members (About Page)'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial (Homepage)', 'verbose_name_plural': 'Testimonials (Homepage)'},
        ),
        migrations.AlterModelOptions(
            name='whytrustus',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Why Trust Us Item (About Page)', 'verbose_name_plural': 'Why Trust Us (About Page)'},
        ),
    ]
