# Generated by Django 5.2.8 on 2025-12-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings (Homepage)', 'verbose_name_plural': 'Site Settings (Homepage)'},
        ),
    ]
