# Generated by Django 5.2.8 on 2025-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Send us a Message', 'verbose_name_plural': 'Send us a Message'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='your@email.com', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Your name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='+27 (0) 123 456 789', max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='What is this about?', max_length=255, verbose_name='Subject'),
        ),
    ]
